import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("node:fs", () => ({
  existsSync: vi.fn(),
  writeFileSync: vi.fn(),
  mkdirSync: vi.fn(),
}));

vi.mock("node:path", async (importOriginal) => {
  const actual = await importOriginal();
  return { ...actual };
});

const { writeFileSync, mkdirSync } = await import("node:fs");
const { generateConfig, writeConfig } = await import("../../src/cliproxy/config-gen.mjs");

/** @returns {import("../../src/cliproxy/accounts.mjs").Account} */
function makeAccount(name, apiKey = "sk-ant-key") {
  return { name, apiKey, addedAt: "2026-01-01T00:00:00.000Z", lastUsed: null };
}

describe("config-gen", () => {
  beforeEach(() => {
    vi.resetAllMocks();
  });

  // ---- generateConfig ----

  describe("generateConfig", () => {
    it("produces YAML with accounts entries", () => {
      const accounts = [
        makeAccount("claude-1", "sk-ant-abc"),
        makeAccount("claude-2", "sk-ant-xyz"),
      ];

      const yaml = generateConfig(accounts);

      expect(yaml).toContain("name: claude-1");
      expect(yaml).toContain("name: claude-2");
    });

    it("includes port setting defaulting to 8317", () => {
      const yaml = generateConfig([]);

      expect(yaml).toContain("port: 8317");
    });

    it("accepts custom port option", () => {
      const yaml = generateConfig([], { port: 9000 });

      expect(yaml).toContain("port: 9000");
    });

    it("includes cache.enabled: true by default", () => {
      const yaml = generateConfig([]);

      expect(yaml).toContain("enabled: true");
    });

    it("respects cacheEnabled: false option", () => {
      const yaml = generateConfig([], { cacheEnabled: false });

      expect(yaml).toContain("enabled: false");
    });

    it("handles empty accounts array with accounts: [] or no entries", () => {
      const yaml = generateConfig([]);

      expect(yaml).toContain("accounts:");
      // No account names expected
      expect(yaml).not.toContain("name: claude");
    });

    it("includes generation comment header", () => {
      const yaml = generateConfig([]);

      expect(yaml).toMatch(/Generated by vein-launch/);
    });

    it("maps account names to api_key env var references", () => {
      const accounts = [makeAccount("claude-1")];

      const yaml = generateConfig(accounts);

      expect(yaml).toContain("api_key:");
    });
  });

  // ---- writeConfig ----

  describe("writeConfig", () => {
    it("writes config YAML to the specified path", () => {
      const result = writeConfig("port: 8317\n", "/some/path/config.yaml");

      expect(result.ok).toBe(true);
      expect(writeFileSync).toHaveBeenCalledWith("/some/path/config.yaml", "port: 8317\n", "utf8");
    });

    it("creates parent directories before writing", () => {
      writeConfig("port: 8317\n", "/deep/nested/path/config.yaml");

      expect(mkdirSync).toHaveBeenCalledWith("/deep/nested/path", { recursive: true });
    });

    it("returns ok: false and message when write fails", () => {
      writeFileSync.mockImplementation(() => {
        throw new Error("Permission denied");
      });

      const result = writeConfig("port: 8317\n", "/forbidden/config.yaml");

      expect(result.ok).toBe(false);
      expect(result.message).toMatch(/Permission denied/);
    });

    it("returns descriptive message on success", () => {
      const result = writeConfig("port: 8317\n", "/out/config.yaml");

      expect(result.ok).toBe(true);
      expect(typeof result.message).toBe("string");
      expect(result.message.length).toBeGreaterThan(0);
    });
  });
});
