import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

/** @typedef {{ name: string, apiKey: string, addedAt: string, lastUsed: string|null }} Account */
/** @typedef {{ ok: boolean, message: string }} Result */

/**
 * @typedef {{ port?: number, cacheEnabled?: boolean }} GenerateOptions
 */

/**
 * Build an accounts block for the YAML output.
 * @param {Account[]} accounts
 * @returns {string}
 */
function buildAccountsBlock(accounts) {
  if (accounts.length === 0) return "accounts: []\n";
  const lines = ["accounts:"];
  for (const { name } of accounts) {
    const envVar = `ANTHROPIC_API_KEY_${name.toUpperCase().replace(/-/g, "_")}`;
    lines.push(`  - name: ${name}`);
    lines.push(`    api_key: \${${envVar}}`);
  }
  return `${lines.join("\n")}\n`;
}

/**
 * Generate a CLIProxy config.yaml string from an accounts list.
 * @param {Account[]} accounts
 * @param {GenerateOptions} options
 * @returns {string}
 */
export function generateConfig(accounts, options = {}) {
  const { port = 8317, cacheEnabled = true } = options;
  return [
    "# Generated by vein-launch — do not edit manually",
    `port: ${port}`,
    "cache:",
    `  enabled: ${cacheEnabled}`,
    buildAccountsBlock(accounts),
  ].join("\n");
}

/**
 * Write a config YAML string to disk, creating parent directories if needed.
 * @param {string} configYaml
 * @param {string} outputPath
 * @returns {Result}
 */
export function writeConfig(configYaml, outputPath) {
  try {
    mkdirSync(dirname(outputPath), { recursive: true });
    writeFileSync(outputPath, configYaml, "utf8");
    return { ok: true, message: `Config written to ${outputPath}` };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return { ok: false, message };
  }
}
